name: Release Deploy Maven Central
run-name: Deploy release artifacts to Maven Central
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy-to-maven-central:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Maven cache
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: checkstyle-files-generator-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Configure GPG
        env:
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: |
          ./.ci/release-configure-gpg.sh

      - name: Configure Maven release settings
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        run: |
          ./.ci/release-configure-maven-settings.sh

      - name: Deploy release artifacts
        run: |
          ./.ci/release-deploy-maven-central.sh
